// WFS v1.0 - dbh_ra9
var opfsRoot;
var metaDir;
var dataDir;
async function init() {
    opfsRoot = await navigator.storage.getDirectory();
    metaDir = await opfsRoot.getDirectoryHandle("handles", { create: true });
    dataDir = await opfsRoot.getDirectoryHandle("objects", { create: true });
    self.postMessage({ contents: "initdone" });
}

function generateUID() {
    const bytes = crypto.getRandomValues(new Uint8Array(32));
    return [...bytes].map(b => b.toString(16).padStart(2, "0")).join("");
}


var FS = {
    eraseall: async function (confirmation) {
        // confirmation MUST be "I understand all data in WFS will be destroyed";
        if (confirmation === "I understand all data in WFS will be destroyed") {
            opfsRoot.removeEntry('handles', { recursive: true });
            opfsRoot.removeEntry('objects', { recursive: true });
            return true;
        } else {
            return false;
        }

    },
    read: async function (path, fromDataDir = false, returnAllData) {
        // Read function generated by ChatGPT
        if (!fromDataDir) {
            let current = metaDir;
            const parts = path.split("/").filter(Boolean);
            console.log(parts);
            for (let i = 0; i < parts.length - 1; i++) {
                current = await current.getDirectoryHandle(parts[i]);
                console.log(current);
            }
            console.log(parts.at(-1));
            const file = await current.getFileHandle(parts.at(-1));
            const data = await file.getFile();
            console.log(data);
            const uid = await data.text();
            console.log("UID for", path, "is", uid);

            return await this.read(uid, true, returnAllData);
        } else {
            const file = await dataDir.getFileHandle(path);
            const data = await file.getFile();
            let content;
            let blob = false;
            if (path.endsWith('_blob')) {
                content = data;
                blob = true;
            } else {
                content = await data.text();
            }
            if (returnAllData === true) {
                return { fileHandle: file, isBlob: blob, content}
            } else {
                return content;
            }
        }
    },
    switchdelete: async function (path, current) {
        const parts = path.split("/").filter(Boolean);
        for (let i = 0; i < parts.length - 1; i++) {
            current = await current.getDirectoryHandle(parts[i]);
        }

        const nameToDelete = parts.at(-1);

        try {
            await current.removeEntry(nameToDelete);
            console.log(`Deleted: ${nameToDelete}`);
            return true;
        } catch (err) {
            console.log(`Failed to delete '${nameToDelete}':`, err);
            return false;
        }
    },
    walkPath: async function (path) {
        if (!path.endsWith("/")) {
            path += "/";
        }

        console.log(path);
        const create = false;
        let current = metaDir;
        const parts = path.split("/").filter(Boolean);
        console.log(parts);

        for (let i = 0; i < parts.length; i++) {
            console.log(`Reading ${parts[i]}`)
            console.log(i, current);
            current = await current.getDirectoryHandle(parts[i], { create });
        }

        let items = {};

        let i = 0;
        for await (const [name, handle] of current.entries()) {
            console.log(`Name: ${name}, Kind: ${handle.kind}, Path: ${path + name}`);
            items[i] = { name: name, kind: handle.kind, path: path + name }
            i++;
        }

        return items;
    },
    switchwrite: async function (path, contents, kind, current, echo) {
        const create = true;
        const parts = path.split("/").filter(Boolean);

        for (let i = 0; i < parts.length - 1; i++) {
            current = await current.getDirectoryHandle(parts[i], { create });
        }

        const file = await current.getFileHandle(parts.at(-1), { create });
        console.log(file, parts.at(-1));
        const writable = await file.createWritable();
        await writable.write(contents);
        await writable.close();
        return true;
    },
    write: async function (path, contents, kind) {
        try {
            async function checkOld() {
                try {
                    let current = metaDir;
                    const parts = path.split("/").filter(Boolean);
                    console.log(parts);
                    for (let i = 0; i < parts.length - 1; i++) {
                        current = await current.getDirectoryHandle(parts[i]);
                        console.log(current);
                    }
                    console.log(parts.at(-1));
                    const file = await current.getFileHandle(parts.at(-1));
                    const data = await file.getFile();
                    const uid = await data.text();
                    console.log("UID for", path, "is", uid);
                    return uid.slice(0, -5);
                } catch (error) {
                    return await generateUID();
                }
            }

            let fileuID = await checkOld();

            console.log(fileuID);

            if (kind === "blob") {
                fileuID = fileuID + "_blob";
                if (!contents instanceof Blob) {
                    contents = new Blob([contents]);
                }
            } else {
                fileuID = fileuID + "_text";
            }

            console.log(`<i> Finished write preparation`);

            const metaHandler = await this.switchwrite(path, fileuID, 'text', metaDir);
            const dataHandler = await this.switchwrite(fileuID, contents, kind, dataDir);

            console.log(metaHandler, dataHandler);
            return true;
        } catch (error) {
            return false;
        }
    }
}

addEventListener('message', async event => {
    console.log(event.data);
    if (event.data.op === "init") {
        try {
            await init();
        } catch (error) {
            console.log(`<!> Filesystem init failed. Details: `, event.data, error);
        }
    } else if (event.data.op === "write") {
        try {
            const wr = await FS.write(event.data.path, event.data.contents, event.data.type);
            console.log(wr);
            self.postMessage({ opID: event.data.opID, op: event.data.op, contents: wr, error: undefined });
        } catch (error) {
            console.log(`<!> Filesystem operation failed. Details: `, event.data, error);
            self.postMessage({ opID: event.data.opID, op: event.data.op, contents: false, error: true });

        }
    } else if (event.data.op === "read") {
        try {
            let wr;
            if (event.data.contents) {
                console.log('<i> preferring uid');
                wr = await FS.read(event.data.contents, true, event.data.type);
            } else {
                wr = await FS.read(event.data.path, undefined, event.data.type);
            }
            self.postMessage({ opID: event.data.opID, op: event.data.op, contents: wr, error: undefined });
        } catch (error) {
            console.log(`<!> Filesystem operation failed. Details: `, event.data, error);
            console.log(error);
            if (error.name.includes('NotFound')) {
                self.postMessage({ opID: event.data.opID, op: event.data.op, contents: false, error: false });
            }
        }
    } else if (event.data.op === "erase") {
        try {
            let wr = await FS.eraseall(event.data.contents);
            self.postMessage({ opID: event.data.opID, op: event.data.op, contents: wr, error: undefined });
        } catch (error) {
            console.log(`<!> Filesystem operation failed. Details: `, event.data, error);
            self.postMessage({ opID: event.data.opID, op: event.data.op, contents: false, error: true });
        }
    } else if (event.data.op === "ls") {
        try {
            let wr;
            console.log(event.data);
            wr = await FS.walkPath(event.data.path);
            self.postMessage({ opID: event.data.opID, op: event.data.op, contents: wr, error: undefined });
            console.log(wr);
        } catch (error) {
            console.log(`<!> Filesystem operation failed. Details: `, event.data, error);
            self.postMessage({ opID: event.data.opID, op: event.data.op, contents: false, error: true });
        }
    }
});